#spring.application.name=gestickets
#spring.datasource.url=jdbc:postgresql://localhost:5432/gestickets
#spring.datasource.username=postgres
#spring.datasource.password=1234
#server.port=8081
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.enabled=true
#spring.application.name=bkedgame
application_name=${application_name}
datasource_url=${datasource_url}
datasource_username=${datasource_username}
datasource_password=${datasource_password}
server_port=${server_port}
jpa_hibernate_ddl-auto=${jpa_hibernate_ddl-auto}
jpa_properties_hibernate_dialect=${jpa_properties_hibernate_dialect}
jpa_show-sql=${jpa_show-sql}
thymeleaf_prefix=${thymeleaf_prefix}
thymeleaf_suffix=${thymeleaf_suffix}
thymeleaf_enabled=${thymeleaf_enabled}
application_name=${application_name}

